export const USER_ROLE = {
  JOB_SEEKER: "JOB_SEEKER",
  COMPANY_MEMBER: "COMPANY_MEMBER",
  COMPANY_OWNER: "COMPANY_OWNER",
  ADMIN: "ADMIN",
};

export const COMPANY_STATUS = {
  ACTIVE: "ACTIVE",
  SUSPENDED: "SUSPENDED",
};
